version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestControls_4_1Project
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: DesignerStepsInCloudEditorPackage
  gitServerName: test
  gitUrl: https://github.com/santhu736852
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: testAssetsOnPrem_4
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
